import { FEATURE_COLOR_PALETTE } from './colorPalette';

/**
 * Pin styles: the glyph drawn inside a pin's teardrop marker. Stored in `features.icon` (§7.1:
 * "icon TEXT -- e.g. 'camp','water','stand','trailhead'"). The artwork is generated by
 * tools/build_pin_icons.mjs, so adding a style means adding its shape there and its id here.
 */
export const PIN_STYLES = [
  { id: 'pin', label: 'Pin' },
  { id: 'camp', label: 'Camp' },
  { id: 'water', label: 'Water' },
  { id: 'stand', label: 'Stand' },
  { id: 'trailhead', label: 'Trailhead' },
  { id: 'peak', label: 'Peak' },
  { id: 'star', label: 'Star' },
  { id: 'flag', label: 'Flag' },
  { id: 'hazard', label: 'Hazard' },
] as const;

export type PinStyleId = (typeof PIN_STYLES)[number]['id'];

export const DEFAULT_PIN_STYLE: PinStyleId = 'pin';

/** Red, so a pin never reads as the blue "you are here" location dot. */
export const DEFAULT_PIN_COLOR: string = FEATURE_COLOR_PALETTE[0];

const KNOWN_STYLES: ReadonlySet<string> = new Set(PIN_STYLES.map((style) => style.id));

/** Anything stored in `icon` that isn't a known style (null, imported free text) falls back to the plain pin. */
export function resolvePinStyle(icon: string | null | undefined): PinStyleId {
  return icon != null && KNOWN_STYLES.has(icon) ? (icon as PinStyleId) : DEFAULT_PIN_STYLE;
}
