import type { ImageSourcePropType } from 'react-native';

import type { PinStyleId } from '../features/pinStyles';

/**
 * Pin artwork, generated by tools/build_pin_icons.mjs. Metro needs every `require` to be a
 * literal path, hence the spelled-out tables.
 *
 * `sdf-*` are signed-distance fields for the map's symbol layers (tinted by `icon-color`);
 * `mask-*` are plain silhouettes for React Native UI, tinted with `Image`'s `tintColor`.
 */
const SDF: Record<PinStyleId | 'body', ImageSourcePropType> = {
  body: require('../../assets/pins/sdf-body.png'),
  pin: require('../../assets/pins/sdf-pin.png'),
  camp: require('../../assets/pins/sdf-camp.png'),
  water: require('../../assets/pins/sdf-water.png'),
  stand: require('../../assets/pins/sdf-stand.png'),
  trailhead: require('../../assets/pins/sdf-trailhead.png'),
  peak: require('../../assets/pins/sdf-peak.png'),
  star: require('../../assets/pins/sdf-star.png'),
  flag: require('../../assets/pins/sdf-flag.png'),
  hazard: require('../../assets/pins/sdf-hazard.png'),
};

export const PIN_MASKS: Record<PinStyleId | 'body', ImageSourcePropType> = {
  body: require('../../assets/pins/mask-body.png'),
  pin: require('../../assets/pins/mask-pin.png'),
  camp: require('../../assets/pins/mask-camp.png'),
  water: require('../../assets/pins/mask-water.png'),
  stand: require('../../assets/pins/mask-stand.png'),
  trailhead: require('../../assets/pins/mask-trailhead.png'),
  peak: require('../../assets/pins/mask-peak.png'),
  star: require('../../assets/pins/mask-star.png'),
  flag: require('../../assets/pins/mask-flag.png'),
  hazard: require('../../assets/pins/mask-hazard.png'),
};

/** Artwork canvas, in image pixels (the pin's tip touches the bottom edge). */
export const PIN_IMAGE_WIDTH = 64;
export const PIN_IMAGE_HEIGHT = 80;

export const PIN_BODY_IMAGE = 'pin-body';
export const PIN_GLYPH_IMAGE_PREFIX = 'pin-glyph-';

/** Every pin image, keyed by the name the symbol layers use, ready for maplibre's `<Images>`. */
export const MAP_PIN_IMAGES: Record<string, { source: ImageSourcePropType; sdf: true }> = Object.fromEntries([
  [PIN_BODY_IMAGE, { source: SDF.body, sdf: true }],
  ...(Object.keys(SDF) as (PinStyleId | 'body')[])
    .filter((key): key is PinStyleId => key !== 'body')
    .map((style) => [`${PIN_GLYPH_IMAGE_PREFIX}${style}`, { source: SDF[style], sdf: true }]),
]);
