#!/usr/bin/env node
/**
 * Bundles map-label glyphs (Noto Sans Regular, SIL OFL 1.1) into the app so
 * text labels render fully offline. MapLibre draws text from signed-distance
 * glyph PBFs that a style normally fetches from a font server; an offline-first
 * app has none, so the app writes these bytes to its documents directory on
 * launch (src/map/glyphs.ts) and points the style's `glyphs` URL at them.
 *
 * Ranges: 0-255 (Basic Latin + Latin-1) and 8192-8447 (general punctuation —
 * curly quotes, en/em dashes, bullets) cover US place/road/trail names.
 *
 * Usage: node tools/build_glyphs.mjs
 */
import { Buffer } from 'node:buffer';
import { writeFile } from 'node:fs/promises';
import path from 'node:path';

const FONT = 'Noto Sans Regular';
const RANGES = ['0-255', '8192-8447'];
const BASE = 'https://demotiles.maplibre.org/font';

const ranges = {};
for (const range of RANGES) {
  const res = await fetch(`${BASE}/${encodeURIComponent(FONT)}/${range}.pbf`);
  if (!res.ok) throw new Error(`glyph range ${range}: HTTP ${res.status}`);
  ranges[range] = Buffer.from(await res.arrayBuffer()).toString('base64');
  console.log(`${range}: ${Math.round((ranges[range].length * 3) / 4 / 1024)} KB`);
}

const source = `// Generated by tools/build_glyphs.mjs — do not edit by hand.
// ${FONT} glyph PBFs (SIL Open Font License 1.1), base64-encoded.
export const GLYPH_FONT_SOURCE = ${JSON.stringify(FONT)};
export const GLYPH_RANGES: Record<string, string> = ${JSON.stringify(ranges, null, 2)};
`;
const out = path.join(import.meta.dirname, '..', 'src', 'map', 'glyphData.ts');
await writeFile(out, source);
console.log(`Wrote ${path.relative(process.cwd(), out)}`);
